### ISSUE TITLE
License

### ISSUE THREAD

**Issue by davidbarratt** [mediamosa/mediamosa-ck#40]
Is this code under an open source license? or is it proprietary? If it has a license could it be added to the root of the repository?

**Comment by rblanker** [comment]
There is a copyright file under the root; COPYRIGHT.MediaMosa.txt which states its GPL2.x. There is no need to add a licence, as its not mandatory to add one as the file above has a link to the licence. But I do agree we need to add one here.

**Comment by rblanker** [comment]
LICENSE.txt has been added to root.
